export const BRANDS = [
  {
    id: 1,
    agencyName: 'Brand Knew',
    brandName: 'Association of Volleyball Professionals',
    cssId: 'AVP',
    focused: true,
    project: 'Membership Portal',
    platform: 'WordPress',
    description:['In 2019, I lead the development of a membership portal for the AVP to allow their existing members to manage, edit, and pay for their membership online within their existing WordPress site. The new portal was created to work with their original membership system, while also rolling out a new tiered system for varying levels of access and benefits, for which AVP already had a separate team overseas working on their API.','This project was completed in 2020, at the peak of the COVID-19 pandemic when lockdown prevented events like volleyball games from being played or attended by fans. Despite this unforseeable setback, the membership portal launched successfully. The portal brought in more than 100,000 unique users and generated over $1 million in revenue within the first year of launch, and is still being used and maintained by the AVP as their online membership portal.'],
    details: ['WordPress', 'Advanced Custom Fields', 'Vue.js', 'SCSS', 'MailGun', 'Postman'],
    url: 'https://avp.com/membership',
    imageType: 'jpg',
  },
  {
    id: 2,
    agencyName: 'Brand Knew',
    brandName: 'The Weitzman Museum of National Jewish Heritage',
    cssId: 'NMAJH',
    focused: false,
    project: 'Virtual Museum',
    platform: 'WordPress',
    description:['During the COVID-19 pandemic, the Weitzman launched a virtual museum experience on their WordPress site to allow visitors an opportunity to enjoy the museum online during lockdown.'],
    url: 'https://theweitzman.org/virtual-museum/',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS'],
    imageType: 'png',
  }, 
  {
    id: 3,
    agencyName: 'Brand Knew',
    brandName: 'Hilarity for Charity',
    cssId: 'HFC',
    focused: false,
    project: 'Modular Email Template',
    platform: 'Mailchimp',
    description:['HFC approached Brand Knew with the goal of creating an editable modular email template with a customizeable color palette and various layout options. I lead the development of this template in close coordiation with our internal designer. The template was developed for the Mailchimp editor and was tested extensively to verify the quality and coherence of the modular capabilities of the layout and styles. This template was used for their primary newsletter, and the level of customization built into the MailChimp template allowed their editor and other members of their team to manage and contribute easily.'],
    url: 'https://wearehfc.org/',
    details: ['Mailchimp', 'HTML', 'CSS', 'Litmus'],
    imageType: 'png',
  },
  {
    id: 4,
    agencyName: 'Brand Knew',
    brandName: 'Goodwill Socal',
    cssId: 'GWSC',
    focused: false,
    project: 'Announcement Banner',
    platform: 'WordPress',
    description:['During the pandemic, Goodwill locations and donation centers throughout Southern California were closed during lockdown. To easily communicate with visitors throughout the region, Goodwill added a customizeable announcement bar to their main WordPress site. Though primarily designed for serious announcements like the pandemic closures, it was editable through the Advanced Custom Fields menu to allow them to feature sales and other timely announcements. The announcement banner is still live and, currently being used to communicate information about the fires occuring through the Los Angeles County in 2025.'],
    url: 'https://www.goodwillsocal.org/',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS'],
    imageType: 'jpg',
  },
  {
    id: 5,
    agencyName: 'Brand Knew',
    brandName: 'StandUp2Cancer',
    cssId: 'SU2C',
    focused: false,
    project: 'Research Finder',
    platform: 'WordPress',
    description:['The Research Finder is a tool designed to be incorporated with the StandUp2Cancer WordPress site to allow visitors to easily filter through hundreds of cancer research journals, studies and trials. When I joined Brand Knew, the tool was primarily being tested and debugged prior to official launch. I helped my other dev to test, debug and fix the finder. I took over the integration of the research finder into the existing WordPress theme, including pagination and filtering, with extra consideration for mobile visitors due to the amount of information condensed into the tables.'],
    url: 'https://standuptocancer.org/research-finder/?type=research_project&orderby=date&order=DESC&current_page=1',
    details: ['WordPress', 'JavaScript/jQuery','JSON','REST API', 'SCSS'],
    imageType: 'jpg',
  },
  {
    id: 6,
    agencyName: 'Brand Knew',
    brandName: 'OneMind',
    cssId: 'Onemind',
    focused: false,
    project: 'OneMind at Work',
    platform: 'WordPress',
    description:['One Mind is a non-profit mental health organization. Shortly after the pandemic began, One Mind launched a mental health initiative for companies and with it, they wanted a microsite dedicated to the topic. The microsite was designed in-house and built to serve as an orientation to their mental health resources relevant to workplace mental health.'],
    url: 'https://onemindatwork.org/',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS'],
    imageType: 'jpg',
  },
  {
    id: 7,
    agencyName: 'Brand Knew',
    brandName: 'Okioki',
    cssId: 'Oki',
    focused: false,
    project: 'Shopify and Marketing Campaigns',
    platform: 'Shopify, Mailchimp',
    description: ['Okioki was an online mattress start up with a Shopify store. For the majority of my time at Brand Knew, our dev team maintained and developed various updates to their store, such as a sitewide cart with a customizeable deal bundler that would watch items added to the cart to suggest relevant items or set pieces, in addition to featuring new items and sales.', 'Brand Knew also ran the Okioki Mailchimp marketing campaign. I met almost daily with the Okioki account manager to translate their upcoming sales and new item launches into their custom designed templates.'],
    url: 'https://theweitzman.org/virtual-museum/',
    details: ['Shopify', 'Liquid', 'JavaScript','Mailchimp', 'HTML', 'CSS', 'Litmus'],
    imageType: 'png',
  },
  {
    id: 8,
    agencyName: 'Digital Operative',
    brandName: 'Outdoor Association Industry',
    cssId: 'OIA',
    focused: true,
    project: 'Outdoor Advocacy Report',
    platform: 'WordPress',
    description:['In addition to maintaining the overall WordPress site for the Outdoor Association Industry, at Digital Operative, myself and one other WordPress developer helped launched an interactive tool for visitors to review the official US Bureau of Economic Analysis report on outdoor recreation economy and advocacy.','The interactive map allows users to easily access the information from the report on the website, in addition to easily accessing the official report documents. The tool is updated annually to reflect the new information from the previous economic year and is still maintained today.'],
    url: 'https://outdoorindustry.org/advocacy',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS', 'JavaScript/jQuery'],
    imageType: 'jpg',
  },
  {
    id: 9,
    agencyName: 'Digital Operative',
    brandName: 'T3Micro',
    cssId: 'T3',
    focused: false,
    project: 'eCommerce and Email Marketing',
    platform: 'Shopify, Mailchimp',
    description:["One approach in Digital Operative's conversion rate optimization strategy for T3Micro included email marketing campaigns to supplement their sales and new product launches on the main Shopify website. In addition to supporting various updates to the Shopify site, such as improving their navigation and creating new product pages, I was also the lead developer of their email marketing campaigns.","Using Foundation for Email to generate the tabled layouts, I worked with the T3 account manager and strategist to create inbox-friendly HTML emails that were rigorously tested in Litmus. More information about DO's CRO strategy can be reviewed on their case study."],
    url:['https://www.digitaloperative.com/case-study/t3-micro/'],
    details:['Shopify','JavaScript','Mailchimp', 'HTML', 'SCSS/CSS', 'Foundation for Email', 'Litmus'],
    imageType: 'jpg',
  },
  {
    id: 10,
    agencyName: 'Digital Operative',
    brandName: 'Nescafé Dolce Gusto',
    cssId: 'NDG',
    focused: false,
    project: 'Email Marketing',
    platform: 'Mailchimp',
    description:['Nescafé Dolce Gusto was another email marketing campaign that I ran while working at Digital Operative. Nescafé focused on sending deal newsletters for every relevant holiday, from Valentines Day to New Years and every holiday in between. These campaigns were also created using Foundation for Email and designed in house at Digital Operative.'],
    details:['Mailchimp', 'HTML', 'CSS', 'Foundation for Email', 'Litmus'],
    imageType: 'jpg',
  },
  {
    id: 10,
    agencyName: 'Ceatus Media Group',
    brandName: 'Ceatus Media Group',
    cssId: 'CMG',
    focused: true,
    project: 'Starter Client WordPress Template',
    platform: 'WordPress',
    description:['Ceatus is a digital marketing company for medical professionals, and I was a senior developer of their in-house dev team, coding custom WordPress themes designed by our internal designer. Before Gutenberg was released in WordPress 5.0, medical professionals, especially in need of photo galleries to demonstrate the quality of their work, were limited to do-it-yourself solutions or fully custom and equivalently priced WordPress themes. Ceatus desired to launch a low-tier, entry level package to offer to their smaller practice clients, such as dental, vision and specific cosmetic procedures.','Working around the capabilities of Advanced Custom Fields and with our in-house designer, Ceatus designed and launched a template that included various layouts, color palettes, fonts and styles, that were easily editable by the practice staff, or intenally if desired. This entry level tier of service for Ceatus was very popular with the intended audience and is still in use today, nearly 10 years later.'],
    url: 'https://www.ceatus.com/',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS'],
    imageType: 'jpg',
  },
  {
    id: 10,
    agencyName: 'Ceatus Media Group',
    brandName: 'Schwartz Laser',
    cssId: 'Schwartz',
    focused: false,
    project: 'Starter Client WordPress Template',
    platform: 'WordPress',
    description:['This is a currently live example of the entry level template for Ceatus Media Group. I left Ceatus in 2017 for Digital Operative, so this theme been updated and modernized to reflect new design standards, however, the structure, foundation and organization of the bespoke capabilities are still intact and an integral part of this template that is still used today by Ceatus.'],
    url: 'https://www.schwartzlaser.com/',
    details: ['WordPress', 'Advanced Custom Fields', 'SCSS'],
    imageType: 'png',
  },
]